[theme]
base = "dark"
primaryColor = "#ff69b4"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1c1c1c"
textColor = "#ffb6c1"
[agent]
name = "Manahil Chatbot"
role = "A helpful and intelligent assistant powered by Gemini"
model = "models/gemini-1.5-flash"
